//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_HELLO_WORLD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public int ID_MATERIAL { get; set; }
        public string MATERIAL_NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
